patch:
  schema/dependencies: {}
  switches:
    - name: ascii_mode
      reset: 0
      states: [ ä¸­æ–‡, è¥¿æ–‡ ]
    - name: emoji_suggestion
      reset: 1
      states: [ "Yes", "No" ]
    - name: full_shape
      states: [ åŠè§’, å…¨è§’ ]
    - name: zh_simp
      reset: 1
      states: [ æ¼¢å­—, æ±‰å­— ]
    - name: ascii_punct
      states: [ ã€‚ï¼Œ, ï¼ï¼Œ ]
  reverse_lookup: {}
  punctuator:
    import_preset: default
    symbols:
      "/fs": [Â½, â€°, Â¼, â…“, â…”, Â¾, â…’ ]
      "/bq": [ğŸ˜‚ï¸, ğŸ˜…ï¸, â˜ºï¸, ğŸ˜±ï¸, ğŸ˜­ï¸, ğŸ˜‡ï¸, ğŸ™ƒï¸, ğŸ¤”ï¸, ğŸ’Šï¸, ğŸ’¯ï¸, ğŸ‘ï¸, ğŸ™ˆï¸, ğŸ’©ï¸, ğŸ˜ˆï¸ ]
      "/dn": [âŒ˜, âŒ¥, â‡§, âŒƒ, â‹, â‡ª, ï£¿, âŒ«, âŒ¦, â†©ï¸, â, â†‘, â†“, â†, â†’, â†–, â†˜, â‡Ÿ, â‡]
      "/fh": [ Â©, Â®, â„—, â„ , â„¢, â„¡, â“˜, â™‚, â™€, â˜‰, â˜Š, â˜‹, â˜Œ, â˜, â˜, â˜‘ï¸, â˜’, â˜œ, â˜, â˜, â˜Ÿ, âœ, âœ„, â™², â™», âš, âš‘, âš ]
      "/xh": [ ï¼Š, Ã—, âœ±, â˜…, â˜†, âœ©, âœ§, â‹, âŠ, â‰, âˆ, â…, âœ¿, âœ²]
    half_shape:
      "#": "#"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      "/": ["/", "Ã·", "ã€"]
      "*": ["*", "Ã—", "Â·", "ãƒ»", "â€»", "ï¼Š", "â‚"]
      '\': ["ã€", '\']
      "'": {pair: ["ã€Œ", "ã€"]}
      "\"": pair: ["â€œ", "â€"]
      "[": ["[", "ã€"]
      "]": ["]", "ã€‘"]
      "{": ["{", "ã€–", "ã€"]
      "}": ["}", "ã€—", "ã€"]
      _: ["â€”â€”", "_"]
      "|": "|"
      "(": ["ï¼ˆ", "("]
      ")": ["ï¼‰", ")"]
      "$": ["Â¥", "$", "â‚¬", "Â£", "Â¢", "Â¤"]
      "<": ["<", "ã€Š", ",", "ã€ˆ", "Â«"]
      ">": [">", "ã€‹", ".", "ã€‰", "Â»"]
  recognizer:
    import_preset: default
    patterns:
      punct: "^/([a-z]+|[0-9]0?)$"
      html: "^<[a-z]+>$"
      code: "[a-zA-Z]+(*$"
      url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]{1,10}[.:_-].*$"

  ### ç²¾ç®€ simp
  "translator/dictionary": pinyin_simp
  "translator/preedit_format": {}
  "speller/algebra/@before 0": xform/^([b-df-hj-np-tv-z])$/$1_/
